"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var PriorityQueue_1 = require("./PriorityQueue");
var Patient_1 = require("./Patient");
var priorityQueue = new PriorityQueue_1.PriorityQueue();
var patient1 = new Patient_1.Patient('Smith', 5);
var patient2 = new Patient_1.Patient('Jones', 4);
var patient3 = new Patient_1.Patient('Fehrenbach', 6);
var patient4 = new Patient_1.Patient('Brown', 1);
var patient5 = new Patient_1.Patient('Ingram', 1);
priorityQueue.enqueue(patient1);
priorityQueue.enqueue(patient2);
priorityQueue.enqueue(patient3);
priorityQueue.enqueue(patient4);
priorityQueue.enqueue(patient5);
console.log('Danh sach benh nhan:');
console.log(priorityQueue.data);
console.log('Benh nhan da duoc kham:');
console.log(priorityQueue.dequeue());
console.log(priorityQueue.dequeue());
console.log(priorityQueue.dequeue());
console.log('Benh nhan con lai:');
console.log(priorityQueue.data);
